# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6c64324577e55ad0482ec8ef43583bb7d5b896561929cf1a9030b81441a0b7f5a5b3076b1bb67682521a5e463c88ec6933b6dc27841410df6b226dc3c0f5dc3

test:
  secret_key_base: 78a61d01e6528422fa08e9dce5186a02acbc5f240210a49df16e747021fe194d0cd62b0dfd1445624715694a7cb5f9c4938e4e2f932edae2c593744a4fc0ecc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
